### PR TITLE
Serverless app dev

### PR DESCRIPTION
**Pull request by jhughes982**
- S3 bucket now private by default to restrict access outside of our web app,
- Authenticated users now gain access to their S3 media items via presigned URL's. The presigned URL is generated when the user makes a request to their file in the web app, so the experience is seamless to the user.
- These presigned URL's have an expiry of 5 minutes to avoid sharing the file for too long. Once the user visits the page again to see their media, a new presigned url is generated.
- File uploads are also handled via presigned a URL 'PUT' request. This generates a temporary presigned url that we make a PUT request against. This allows us to upload files directly to S3 which bypasses lambda altogether and removes any heavy lifting for lambda when uploading the file.
- For more info on the use of presigned urls see [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html)
- I would appreciate if the above functionality could be tested.
- I have also created issues for us to review, mostly related to double checking our created AWS policies and configs and making sure to restrict access where necessary (i.e. least privilege principal).

### CODE REVIEW

**Review by pweschmidt — COMMENTED** [review]
Hi James, 
many thanks for this pull request re the S3 bucket for media. Not so much a comment as a question, really: I see that you have to call the S3 bucket in the React code by name. We then have to do the same in the terraform script. There is a risk that a typo gets introduced in either resulting in an error that the bucket doesn't exist. I am wondering if there is a way we can define strings (as environment variables?) that can be used by both terraform and React? Or is there another way?

**Review by pweschmidt — APPROVED** [review]

**Comment by jhughes982** [comment]
Hi Peter,

I documented this as an issue (#19) so I think it's definitely worth exploring adding our AWS data (e.g. S3 bucket name) as environment variables rather than hardcoding it within our lambda functions.

I know you can add environment variables via the AWS console when setting up your lambda functions, but have not explored how this works in Terraform. But I would imagine there will be a way to do this. I would need to learn more about Terraform though.

**Comment by pweschmidt** [comment]
Thanks for the prompt response, James. Yes, I think environment variables might be a good solution. I need to look up how we can use this in terraform as well as in React. I guess in React, an environment variable gets resolved/filled in at build time? Terraform already uses some environment variables for the AWS secret and client keys as well as the region I believe.

**Comment by jhughes982** [comment]
React does populate environment variables during build time. Right now we are only using one environment variable in React:`REACT_APP_BACKEND_URL` which sets the API Gateway URL endpoint. No other environment variables are needed for the React frontend.

We hardcode other AWS config settings (e.g. S3Bucket) in our lambda functions (i.e. `serverless-app/aws/lambda-functions`) which is not an optimal solution (as you said). As soon as we figure out how to populate these as environment variables in our lambda functions, we can remove the hardcoded variables.

If any of that needs further explanation, happy to have a quick call.

**Pull request merged**
